language: generic 

dist: focal
addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/redis-server'
    packages:
      - cmake
      - texlive-full
      - texlive-latex-extra
      - texlive-fonts-extra
      - texlive-lang-cyrillic
      - texlive-lang-greek
      - texlive-bibtex-extra
      - texlive-fonts-extra

script:
    ############################################################################
    # Build main
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake ../
     - make
